#pragma once
#include "cinder/CinderResources.h"

#define RES_LANTERNGLOW_PNG	CINDER_RESOURCE( resources/, lanternGlow.png,	150, IMAGE )
#define RES_GLOW_PNG		CINDER_RESOURCE( resources/, glow.png,			151, IMAGE )
#define RES_NEBULA_PNG		CINDER_RESOURCE( resources/, nebula.png,		152, IMAGE )
#define RES_BUBBLE_PNG		CINDER_RESOURCE( resources/, bubble.png,		153, IMAGE )
#define RES_BG_PNG			CINDER_RESOURCE( resources/, bg.png,			154, IMAGE )
#define RES_TITLE_PNG		CINDER_RESOURCE( resources/, title.png,			155, IMAGE )
#define RES_PASSTHRU_VERT	CINDER_RESOURCE( resources/, passThru.vert,		160, GLSL )
#define RES_VELOCITY_FRAG	CINDER_RESOURCE( resources/, Velocity.frag,		161, GLSL )
#define RES_POSITION_FRAG	CINDER_RESOURCE( resources/, Position.frag,		162, GLSL )
#define RES_P_VELOCITY_FRAG CINDER_RESOURCE( resources/, P_Velocity.frag,	163, GLSL )
#define RES_P_POSITION_FRAG CINDER_RESOURCE( resources/, P_Position.frag,	164, GLSL )
#define RES_LANTERN_VERT	CINDER_RESOURCE( resources/, lantern.vert,		165, GLSL )
#define RES_LANTERN_FRAG	CINDER_RESOURCE( resources/, lantern.frag,		166, GLSL )
#define RES_ROOM_VERT		CINDER_RESOURCE( resources/, room.vert,			167, GLSL )
#define RES_ROOM_FRAG		CINDER_RESOURCE( resources/, room.frag,			168, GLSL )
#define RES_VBOPOS_VERT		CINDER_RESOURCE( resources/, VboPos.vert,		169, GLSL )
#define RES_VBOPOS_FRAG		CINDER_RESOURCE( resources/, VboPos.frag,		170, GLSL )
#define RES_P_VBOPOS_VERT	CINDER_RESOURCE( resources/, P_VboPos.vert,		171, GLSL )
#define RES_P_VBOPOS_FRAG	CINDER_RESOURCE( resources/, P_VboPos.frag,		172, GLSL )
#define RES_GLOW_FRAG		CINDER_RESOURCE( resources/, glow.frag,			173, GLSL )
#define RES_NEBULA_FRAG		CINDER_RESOURCE( resources/, nebula.frag,		174, GLSL )
